### ISSUE TITLE
라이선스가 어떻게 되나요?

### ISSUE THREAD

**Issue by copyrat90** [RanolP/dalmoori-font#28]
## 라이선스

- 소스 코드: MIT
- 글꼴 파일: SIL OFL 1.1

* * *

`README.md` 엔 저렇게 돼 있는데, `LICENSE` 파일은 또  `Apache-2.0` 이라고 돼 있어서 헷갈리네요

**Comment by RanolP** [comment]
앗 Apache 2.0이 맞습니다. README.md를 안 고쳤나보군요
