### ISSUE TITLE
GitHub Actions 를 이용해 Continuous Deployment 구현

### ISSUE THREAD

**Issue by Alex4386** [RanolP/dalmoori-font#4]
GitHub Actions를 이용해 폰트를 자동으로 생성해 Artifact에 저장하도록 하면 좋을 것 같습니다.

**Comment by RanolP** [comment]
결국 한글날 지나고도 release 내는 actions 못 만들었다 으악

**Comment by RanolP** [comment]
이제 잘 나온다 와!!!

https://github.com/RanolP/dalmoori-font/releases/tag/v0.100
