### ISSUE TITLE
Docs에서 에셋을 제대로 불러오지 못하는 문제

### ISSUE THREAD

**Issue by ShapeLayer** [RanolP/dalmoori-font#8]
에셋 경로를 `path`가 아니라 `/path`로 지정해서 발생하는 것으로 추정됨
`assets/css/common.css` `/assets/css/common.css`

> 전 컴퓨터 놓고 밖에 공부하러 나와서 저녁때쯤에야 손볼 수 있을것 같네요

**Comment by ShapeLayer** [comment]
해결 방법:
`config.yml`의 baseurl 설정 후 에셋을 직접 연결

**Comment by RanolP** [comment]
해결은 된 것 같은데 이번엔 마크다운이 말썽
